datasource:
  driver-class-name: "com.mysql.jdbc.Driver"
  url: "jdbc:mysql://115.68.184.127:3306/test?useUnicode=true&charaterEncoding=utf-8"
  user-name: "eastflag"
  password: "dklee123"
  initial-size: 10
  max-active: 10
  max-idle: 10
  min-idle: 10
  max-wait: 3000